# Generated by Django 4.2.2 on 2023-06-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatwedo', models.TextField()),
                ('mission', models.TextField()),
            ],
        ),
    ]
