# Generated by Django 4.2.2 on 2023-06-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField()),
            ],
        ),
    ]
