# Generated by Django 4.2.2 on 2023-06-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empower', '0002_contactpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='contact',
            new_name='contactinfo',
        ),
    ]
