# Generated by Django 4.2.2 on 2023-06-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empower', '0003_rename_contact_contactpage_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
