# Generated by Django 4.2.2 on 2023-06-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empower', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='bannerColor',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='bannerSize',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
