# Generated by Django 4.2.2 on 2023-06-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empower', '0008_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripeid',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
