# Generated by Django 4.2.2 on 2023-06-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empower', '0009_product_stripeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
